import { useState, useRef } from "react";
import "./App.css";

const API = "http://localhost:8000";
const HISTORY_KEY = "aitd_history";
const loadHistory = () => { try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]"); } catch { return []; } };
const saveHistory = (h) => localStorage.setItem(HISTORY_KEY, JSON.stringify(h));

function ResultCard({ result, loading }) {
  if (!result && !loading) return null;
  const isAI = result?.label === "IA";
  return (
    <div className={`result-card ${isAI ? "result-card--ai" : "result-card--human"}`}>
      {loading ? <div className="spinner" /> : (
        <>
          <div className={`result-icon result-icon--${isAI ? "ai" : "human"}`}>
            {isAI ? "🤖" : "✍️"}
          </div>
          <div className={`result-label result-label--${isAI ? "ai" : "human"}`}>
            {isAI ? "AI Generated" : "Human Written"}
          </div>
          <p className="result-desc">
            {isAI
              ? "This text was most likely generated by an artificial intelligence model."
              : "This text appears to have been written by a human author."}
          </p>
          <div className="result-model">CNN Model · 99.8% accuracy</div>
        </>
      )}
    </div>
  );
}

function HistoryItem({ item, onSelect }) {
  const isAI = item.label === "IA";
  return (
    <button className="hist-item" onClick={() => onSelect(item.text)}>
      <div className="hist-meta">
        <div className="hist-dot" style={{ background: isAI ? "#f28baa" : "#4ee6b0" }} />
        <span>{isAI ? "AI Generated" : "Human Written"}</span>
        <span>·</span>
        <span>{item.time}</span>
      </div>
      <div className="hist-text">{item.text.slice(0, 60)}…</div>
    </button>
  );
}

export default function App() {
  const [text, setText]         = useState("");
  const [result, setResult]     = useState(null);
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState("");
  const [history, setHistory]   = useState(loadHistory);
  const [showHist, setShowHist] = useState(false);
  const textareaRef = useRef(null);
  const wordCount = text.trim() ? text.trim().split(/\s+/).length : 0;

  const analyze = async () => {
    if (!text.trim()) return;
    setLoading(true); setError(""); setResult(null);
    try {
      const res  = await fetch(`${API}/predict`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });
      if (!res.ok) throw new Error();
      const data = await res.json();
      setResult(data);
      const entry = { text, label: data.label,
        time: new Date().toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" }) };
      const next = [entry, ...history].slice(0, 20);
      setHistory(next); saveHistory(next);
    } catch {
      setError("Cannot reach the API. Make sure FastAPI is running on port 8000.");
    } finally { setLoading(false); }
  };

  const paste = async () => { const t = await navigator.clipboard.readText(); setText(t); textareaRef.current?.focus(); };
  const clear = () => { setText(""); setResult(null); setError(""); };

  return (
    <div className="app">
      {/* Background layers */}
      <div className="bg-scene">
        <div className="orb orb-1" />
        <div className="orb orb-2" />
        <div className="orb orb-3" />
        <div className="orb orb-4" />
        <div className="shard shard-1" />
        <div className="shard shard-2" />
        <div className="shard shard-3" />
        <div className="shard shard-4" />
        <div className="shard shard-5" />
        <div className="shard shard-6" />
      </div>
      <div className="bg-grid" />
      <div className="particles">
        {[...Array(8)].map((_, i) => <div key={i} className="particle" />)}
      </div>
      <div className="beam beam-1" />
      <div className="beam beam-2" />
      <div className="beam beam-3" />

      <header className="header">
        <div className="logo">
          <div className="logo-icon">🔍</div>
          <span className="logo-text">AIDetect</span>
          <span className="logo-badge">CNN · 99.8%</span>
        </div>
        <button
          className={`hist-btn ${showHist ? "hist-btn--active" : ""}`}
          onClick={() => setShowHist(s => !s)}
        >
          History
          {history.length > 0 && <span className="hist-badge">{history.length}</span>}
        </button>
      </header>

      <main className="main">
        {showHist && (
          <aside className="history-panel">
            <div className="history-header">
              <span>Recent Analyses</span>
              <button className="clear-hist" onClick={() => { setHistory([]); saveHistory([]); }}>Clear all</button>
            </div>
            {history.length === 0
              ? <div className="hist-empty">No analyses yet.</div>
              : history.map((item, i) => (
                  <HistoryItem key={i} item={item} onSelect={t => { setText(t); setShowHist(false); }} />
                ))
            }
          </aside>
        )}

        <div className="center">
          <div className="hero">
            <div className="hero-eyebrow">✦ Deep Learning Text Analysis</div>
            <h1 className="title">Is this text <span className="accent">AI</span> or Human?</h1>
            <p className="subtitle">
              Paste any text and our CNN model will instantly detect
              whether it was written by a human or generated by AI.
            </p>
          </div>

          <div className="editor-card">
            <div className="editor-toolbar">
              <span className="word-count">{wordCount} words</span>
              <div className="toolbar-actions">
                <button className="tool-btn" onClick={paste}>Paste</button>
                <button className="tool-btn" onClick={clear}>Clear</button>
              </div>
            </div>
            <textarea
              ref={textareaRef}
              className="editor"
              value={text}
              onChange={e => setText(e.target.value)}
              placeholder="Paste or type the text you want to analyze…"
              rows={8}
            />
            <div className="editor-footer">
              {error && <span className="error-msg">⚠ {error}</span>}
              <button
                className="analyze-btn"
                onClick={analyze}
                disabled={loading || !text.trim()}
              >
                {loading
                  ? <><span className="btn-spinner" /> Analyzing…</>
                  : "Analyze Text →"
                }
              </button>
            </div>
          </div>

          {(result || loading) && (
            <div className="results">
              <ResultCard result={result} loading={loading} />
            </div>
          )}
        </div>
      </main>
    </div>
  );
}